### ISSUE TITLE
Annotation doesn't match with complete data, and the training data only covers small part of complete data

### ISSUE THREAD

**Issue by ShixuanGu** [intra3d2019/IntrA#19]
The annotated data is not matched with the complete data.
e.g. there are no matched point clouds in the complete data (**ArteryObjAN1.obj**) for the point clouds in (**AN1-_norm.ad**). 
![image](https://user-images.githubusercontent.com/44287806/183757619-890477b6-20f2-45d8-9254-7b3e1c6da9bd.png)

**Comment by ShixuanGu** [comment]
Also, the data size generated for model training is far smaller than the complete data, e.g., if you sum up the size of ArteryObjAN1-x.ad, it will be 12685 points while for ArteryObjAN1.obj it contains 40153. And the training data doesn't even contain the aneurysm from ArteryObjAN1.
![image](https://user-images.githubusercontent.com/44287806/183780787-116f60dd-ccd4-4906-a388-3d18d44e7c24.png)

red are the batches you generate for ML, green are the annotated aneurysm parts, blue is the  complete data

**Comment by ShixuanGu** [comment]
Why there's no label contained for your generated data. (labels are all set as 0)

**Comment by KeepThinkingYX** [comment]
I have replied to your email and have sent you the data.
Please contact me (Xi Yang) if anyone else needs it.
