### ISSUE TITLE
Number of input points in experiments

### ISSUE THREAD

**Issue by suprosanna** [intra3d2019/IntrA#3]
![image](https://user-images.githubusercontent.com/16708186/76321091-d6417880-62e1-11ea-865d-5a49fddf685b.png)
This is the histogram of the number of points in the samples from the segmentation task. In the paper, up to 2048 input points from each sample are used. For the samples which have a lesser number of points than the experimental requirements, is there any sort of upsampling involved?

**Comment by intra3d2019** [comment]
Nope, random sampling allows reduplicate points, according to the implementation of point-based methods.

**Comment by suprosanna** [comment]
And does it work the same way in meshCNN?

**Comment by intra3d2019** [comment]
The data processing of meshCNN is different, please check their instruction, here
https://github.com/ranahanocka/MeshCNN/

**Comment by suprosanna** [comment]
Thanks!
